spring:
  application:
    name: cartserv
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: cart-queue
    exchange: cart
    routing-key: cart.*
  data:
    cache:
      type: redis
    redis:
      port: 6379
      host: localhost
server:
  port: 9400