server:
  port: 9200

spring:
  application:
    name: categoryserv
  datasource:
    url: jdbc:postgresql://localhost:5432/categorydb
    username: postgres
    password: TestPassword1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

