spring:
  application:
    name: notificationserv
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: notification
    schema-action: CREATE_IF_NOT_EXISTS
    request.timeout: 10s
    connection.connect-timeout: 10s
    connection.init-query-timeout: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: notification-queue
    exchange: notification
    routing-key: notification.*
server:
  port: 9700
