server:
  port: 9500

spring:
  application:
    name: orderserv
  data:
    couchbase:
      auto-index: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: order-queue
    exchange: orders
    routing-key: order.*

management:
  endpoints:
    web:
      exposure:
        include: '*'