spring:
  application:
    name: productserv
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_db
    redis:
      host: localhost
      port: 6379
server:
  port: 9300